General:
    comment: 
    seed: 2021
    fp16: True
    amp_level: O2
    precision: 32
    multi_gpu_mode: dp
    gpus: [0]
    epochs: &epoch 200 
    grad_acc: 2
    frozen_bn: False
    patience: 40
    server: train #train #test
    log_path: logs/

Data:
    dataset_name: Biliary_Atresia_data
    data_shuffle: False
    data_dir: /Path/to/your/pt_files/from/CLAM
    label_dir: dataset_csv/TCGA-Lung/
    fold: 0
    nfold: 4

    train_dataloader:
        batch_size: 1 
        num_workers: 8

    test_dataloader:
        batch_size: 1
        num_workers: 8

Model:
    name: MKMIL
    n_classes: 2
    dropout: 0.5
    act: relu
    n_features: 1024
    layer: 2
    rate: 10
    type: AFWMamba


Optimizer:
    opt: lookahead_radam
    lr: 0.0002
    opt_eps: null 
    opt_betas: null
    momentum: null 
    weight_decay: 0.00001

Loss:
    base_loss: CrossEntropyLoss

